#!/bin/bash
# HP EliteBook 840 G4 Create Install SSD
# By chris1111
# Vars
apptitle="Create Install SSD"
version="1.0"
# Set Icon directory and file 
export ICNS=$(dirname "${0}")
iconfile="$ICNS/applet.icns"
# Set Package directory and file 
export PKG=$(dirname "${0}")
Packagefile="$PKG/OpenCore.pkg"

echo "HP EliteBook 840 G4
Create Install SSD"
echo "-------------------------------------"


response=$(osascript -e 'tell app "System Events" to display dialog "
Format your SSD or HD drive with Disk Utility.
Format your SSD into a single partition
macOS Extended Logs/GUID Partition
Give it whatever name you want
After formatting, you must exit Disk Utility to continue installation\nCancel = EXIT" buttons {"Cancel", "Disk Utility"} default button 2 with title "'"$apptitle"' '"$version"'" with icon POSIX file "'"$iconfile"'"  ')

action=$(echo $response | cut -d ':' -f2)

# Exit if Canceled
if [ ! "$action" ] ; then
  osascript -e 'display notification "Program closing" with title "'"$apptitle"'" subtitle "User cancelled"'
  exit 0
  osascript -e 'quit app "HP EliteBook 840 G4"'
fi

osascript -e 'display notification "Program start" with title "'"$apptitle"'" subtitle "User select Disk Utility"' 
Sleep 1

osascript <<EOD
do shell script "open -F -a 'Disk Utility'"delay 1tell application "Disk Utility"	activateend tellrepeat	if application "Disk Utility" is not running then exit repeatend repeat
EOD


# Get input folder of usbdisk disk 
  usbdiskpath=`/usr/bin/osascript << EOT
    tell application "Finder"
        activate
        set folderpath to choose folder default location "/Volumes" with prompt "Choose your SSD / HD"
    end tell 
    return (posix path of folderpath) 
  EOT`

  # Cancel is user selects Cancel
  if [ ! "$usbdiskpath" ] ; then
    osascript -e 'display notification "Program closing" with title "'"$apptitle"'" subtitle "User cancelled"'
    exit 0
  fi

# Parse disk volume
usbdisk=$( echo $usbdiskpath | awk -F '\/Volumes\/' '{print $2}' | cut -d '/' -f1 )
disknum=$( diskutil list | grep "$usbdisk" | awk -F 'disk' '{print $2}' | cut -d 's' -f1 )
devdisk="/dev/disk$disknum"
# check rdisk
devdiskr="/dev/rdisk$disknum"
# Get Drive size
drivesize=$( diskutil list | grep "disk$disknum" | grep "0\:" | cut -d "*" -f2 | awk '{print $1 " " $2}' )

source=$inputfile
dest="$drivesize $usbdisk (disk$disknum)"
outputfile=$devdiskr
check=$source
echo "⬇︎ "
echo "-------------------------------------"
echo "$usbdiskpath " 
echo "-------------------------------------"
Sleep 2	


# Get image file location
  imagepath=`/usr/bin/osascript << EOT
    tell application "Finder"
        activate
        set imagefilepath to choose file default location "/Applications" with prompt "Choose your Install macOS.app"
    end tell 
    return (posix path of imagefilepath) 
  EOT`

  # Cancel is user selects Cancel
  if [ ! "$imagepath" ] ; then
    osascript -e 'display notification "Program closing" with title "'"$apptitle"'" subtitle "User cancelled"'
    exit 0
  fi


# Parse vars for Install macOS
inputfile=$imagepath
echo "⬇︎ "	
echo "-------------------------------------"
echo "$inputfile "
echo "-------------------------------------"
Sleep 2



# Confirmation
response=$(osascript -e 'tell app "System Events" to display dialog "Please confirm your choice then press the OK button\n\nSource: \n'"$imagepath"' \n\nDestination: \n'"$usbdiskpath"' \n\n\nThe volume will be use for the Installer macOS" buttons {"Cancel", "OK"} default button 2 with title "'"$apptitle"' '"$version"'" with icon POSIX file "'"$iconfile"'" ')
answer=$(echo $response | grep "OK")

# Cancel is user does not select OK
if [ ! "$answer" ] ; then
  osascript -e 'display notification "Program closing" with title "'"$apptitle"'" subtitle "User cancelled"'
  exit 0
fi

echo "-------------------------------------"
echo "Confirmation OK ✅ "
echo "-------------------------------------"



echo "Install OpenCore 
Type your password: " 

# run the pkg
sudo installer -allowUntrusted -verboseR -pkg /"$Packagefile" -target /"$usbdiskpath"
Sleep 1
chflags hidden /"$usbdiskpath"/Private
chflags hidden /"$usbdiskpath"/Library
echo " "
echo "macOS startosinstall
The system will reboot when finished. " 

sudo "$inputfile"/Contents/Resources/startosinstall --agreetolicense --volume /"$usbdiskpath" --rebootdelay 5 --nointeraction

